# Generated by Django 4.2.4 on 2023-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputTime', models.DateField()),
                ('expensesTime', models.DateField()),
                ('expenses', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
    ]
