# Generated by Django 4.2.4 on 2023-09-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='time',
            field=models.DateField(),
        ),
    ]
