# Generated by Django 4.2.4 on 2023-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_dailysales_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('customer_id', models.IntegerField(blank=True)),
                ('product_id', models.IntegerField()),
                ('number_sales', models.IntegerField()),
            ],
        ),
    ]
