# Generated by Django 4.2.4 on 2023-08-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majoo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='ImportSalesFile',
        ),
    ]
