# Generated by Django 4.2.4 on 2023-08-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majoo', '0002_rename_sales_importsalesfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sales', models.IntegerField()),
                ('grossProfit', models.IntegerField()),
                ('nProd', models.IntegerField()),
            ],
        ),
    ]
