# Generated by Django 4.2.4 on 2023-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majoo', '0005_alter_importsalesfile_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsalesfile',
            name='filepath',
            field=models.CharField(default=None, max_length=256, verbose_name='filepath'),
        ),
    ]
