# Generated by Django 4.2.4 on 2023-08-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majoo', '0009_remove_importsalesfile_filepath_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySales',
        ),
        migrations.AlterField(
            model_name='importsalesfile',
            name='filename',
            field=models.FileField(default=None, max_length=256, upload_to='assets/majoo_files', verbose_name='filename'),
        ),
    ]
