# Generated by Django 4.2.4 on 2023-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majoo', '0010_delete_dailysales_alter_importsalesfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsalesfile',
            name='processing_start_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='processing_start_time'),
        ),
        migrations.AlterField(
            model_name='importsalesfile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Request Importing'), (2, 'Done'), (3, 'Error')], default=1, verbose_name='status'),
        ),
    ]
